import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <>
          {/* NavBar */}
          <nav
            className=" bg-bgColor p-[15px] flex justify-between items-center shadow-2xl z-1 "
            style={{
              boxShadow: "-19px 6px 18px 15px #000",
              position: "sticky",
              zIndex: 1,
              top: 0,
            }}
          >
            {/* LeftSide */}
            <ul className="flex gap-5 items-center text-[20px]">
              <li className="text-[2.5em]">LOGO</li>
              <li>Home</li>
              <li>Movies</li>
              <li>Price</li>
              <li>Contact Us</li>
            </ul>
            {/* RightSide */}
            <div className="flex gap-3 items-center">
              <input
                type="text"
                placeholder="Find Movies, TV shows and"
                className="p-2 border-none rounded-xl"
              />
              <select name="" id="" className="text-black bg-none rounded-md">
                <option value="">ENG</option>
                <option value="">ENG</option>
                <option value="">ENG</option>
                <option value="">ENG</option>
              </select>
              <i className="fa-solid fa-globe" />
              <button className="bg-gradient-to-tr from-purple-500 to-indigo-500 py-[15px] px-[31px] rounded-[30px]">
                Subscribe
              </button>
            </div>
          </nav>
        </>

        {children}
      </body>
    </html>
  );
}
